-- MySQL Script generated by MySQL Workbench
-- dom 21 mar 2021 09:19:19 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airTickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airTickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airTickets` ;
USE `airTickets` ;

-- -----------------------------------------------------
-- Table `airTickets`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airTickets`.`User` (
  `ID` VARCHAR(45) NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Pk_Id_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `User_UNIQUE` (`User` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airTickets`.`InfoUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airTickets`.`InfoUser` (
  `ID` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `DateBirthday` DATETIME NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `PhoneWork` INT NOT NULL,
  `CellPhone` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `PK_Id_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `airTickets`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `airTickets`;
INSERT INTO `airTickets`.`User` (`ID`, `User`, `Password`, `Role`) VALUES ('304760577', 'bryanjsb', '123456', 'Admin');
INSERT INTO `airTickets`.`User` (`ID`, `User`, `Password`, `Role`) VALUES ('103550345', 'Alex', '123456', 'User');

COMMIT;


-- -----------------------------------------------------
-- Data for table `airTickets`.`InfoUser`
-- -----------------------------------------------------
START TRANSACTION;
USE `airTickets`;
INSERT INTO `airTickets`.`InfoUser` (`ID`, `Name`, `LastName`, `email`, `DateBirthday`, `Address`, `PhoneWork`, `CellPhone`) VALUES ('304760577', 'Bryan', 'Sánchez Brenes', 'bryan.jsb.1801@gmail.com', '1994-01-18', 'Cartago, Costa Rica', 71464730, 71464730);
INSERT INTO `airTickets`.`InfoUser` (`ID`, `Name`, `LastName`, `email`, `DateBirthday`, `Address`, `PhoneWork`, `CellPhone`) VALUES ('103550345', 'Alex', 'Lopez ', 'Lopez', '1990-12-31', 'Heredia, Costa Rica', 88888888, 88888888);

COMMIT;

