-- MySQL Script generated by MySQL Workbench
-- Thu Apr  8 11:23:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airTickets
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airTickets` ;

-- -----------------------------------------------------
-- Schema airTickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airTickets` ;
USE `airTickets` ;

-- -----------------------------------------------------
-- Table `airTickets`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airTickets`.`User` ;

CREATE TABLE IF NOT EXISTS `airTickets`.`User` (
  `ID` VARCHAR(45) NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Pk_Id_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `User_UNIQUE` (`User` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airTickets`.`InfoUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airTickets`.`InfoUser` ;

CREATE TABLE IF NOT EXISTS `airTickets`.`InfoUser` (
  `User_ID` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `DateBirthday` DATETIME NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `PhoneWork` INT NOT NULL,
  `CellPhone` INT NOT NULL,
  INDEX `fk_InfoUser_User_idx` (`User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_InfoUser_User`
    FOREIGN KEY (`User_ID`)
    REFERENCES `airTickets`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airTickets`.`Vuelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airTickets`.`Vuelo` ;

CREATE TABLE IF NOT EXISTS `airTickets`.`Vuelo` (
  `idvuelo` INT NOT NULL,
  `Origen` VARCHAR(45) NOT NULL,
  `Destino` VARCHAR(45) NULL,
  `FechaIda` DATETIME NOT NULL,
  `fechaRegreso` DATETIME NULL,
  `cantidadPasajeros` INT NOT NULL,
  `descuento` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idvuelo`),
  UNIQUE INDEX `idvuelo_UNIQUE` (`idvuelo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airTickets`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airTickets`.`Payment` ;

CREATE TABLE IF NOT EXISTS `airTickets`.`Payment` (
  `creditCardNumber` INT NOT NULL,
  `User_ID` VARCHAR(45) NOT NULL,
  `expiration` INT NOT NULL,
  `cvv` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `nameCard` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`creditCardNumber`),
  INDEX `fk_Payment_User1_idx` (`User_ID` ASC) VISIBLE,
  UNIQUE INDEX `creditCardNumber_UNIQUE` (`creditCardNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `airTickets`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airTickets`.`Reservacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airTickets`.`Reservacion` ;

CREATE TABLE IF NOT EXISTS `airTickets`.`Reservacion` (
  `idReservacion` INT NOT NULL,
  `User_ID` VARCHAR(45) NOT NULL,
  `Vuelo_idvuelo` INT NOT NULL,
  `Payment_creditCardNumber` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idReservacion`),
  INDEX `fk_Reservacion_User1_idx` (`User_ID` ASC) VISIBLE,
  INDEX `fk_Reservacion_Vuelo1_idx` (`Vuelo_idvuelo` ASC) VISIBLE,
  INDEX `fk_Reservacion_Payment1_idx` (`Payment_creditCardNumber` ASC) VISIBLE,
  UNIQUE INDEX `idReservacion_UNIQUE` (`idReservacion` ASC) VISIBLE,
  CONSTRAINT `fk_Reservacion_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `airTickets`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_Vuelo1`
    FOREIGN KEY (`Vuelo_idvuelo`)
    REFERENCES `airTickets`.`Vuelo` (`idvuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_Payment1`
    FOREIGN KEY (`Payment_creditCardNumber`)
    REFERENCES `airTickets`.`Payment` (`creditCardNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `airTickets`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `airTickets`;
INSERT INTO `airTickets`.`User` (`ID`, `User`, `Password`, `Role`) VALUES ('304760577', 'bryanjsb', '123456', 'Admin');
INSERT INTO `airTickets`.`User` (`ID`, `User`, `Password`, `Role`) VALUES ('103550345', 'Alex', '123456', 'User');

COMMIT;


-- -----------------------------------------------------
-- Data for table `airTickets`.`InfoUser`
-- -----------------------------------------------------
START TRANSACTION;
USE `airTickets`;
INSERT INTO `airTickets`.`InfoUser` (`User_ID`, `Name`, `LastName`, `email`, `DateBirthday`, `Address`, `PhoneWork`, `CellPhone`) VALUES ('304760577', 'Bryan', 'Sánchez Brenes', 'bryan.jsb.1801@gmail.com', '1994-01-18', 'Cartago, Costa Rica', 71464730, 71464730);
INSERT INTO `airTickets`.`InfoUser` (`User_ID`, `Name`, `LastName`, `email`, `DateBirthday`, `Address`, `PhoneWork`, `CellPhone`) VALUES ('103550345', 'Alex', 'Lopez ', 'Lopez', '1990-12-31', 'Heredia, Costa Rica', 88888888, 88888888);

COMMIT;

