-- MySQL Script generated by MySQL Workbench
-- lun 15 mar 2021 21:12:15 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airTickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airTickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airTickets` ;
USE `airTickets` ;

-- -----------------------------------------------------
-- Table `airTickets`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airTickets`.`Login` (
  `User` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `airTickets`.`PersonalInformation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airTickets`.`PersonalInformation` (
  `PK_User` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Age` INT NULL,
  PRIMARY KEY (`PK_User`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
